version: "3.6"
services:

  api:
    build: .
    environment:
      DATABASE_NAME: "tyre_app"
      IP_SERVER: "167.235.253.89"
      IP_AUTH_SERVER: "167.235.253.89"
      PORT_AUTH_SERVER: 10099
      PORT_SERVER: 10020
      DVLA_API: "85d27fa8-7cca-4429-a0d4-cb8798fd68ee"

    volumes:
      - ./:/main
#    ports:
#      - "10099:10099"
    network_mode: "host"
