version: "3.6"
services:

  api:
    build: .
    environment:
      DATABASE_NAME: "tyre_app"
      IP_SERVER: "167.235.253.89"
      PORT_AUTH_SERVER: "167.235.253.89"
      ip_auth_port: 10099
      PORT_SERVER: 10020

    volumes:
      - ./:/main
#    ports:
#      - "10099:10099"
    network_mode: "host"
