version: "3.6"
services:

  api:
    build: .
    environment:
      DATABASE_NAME: "tyre_app"
      IP_SERVER: "167.235.253.89"
      IP_AUTH_SERVER: "167.235.253.89"
      IP_FILE_SERVER: "167.235.253.89"
      PORT_AUTH_SERVER: 10099
      PORT_SERVER: 10020
      PORT_FILE_SERVER: 10090
      DVLA_API: "85d27fa8-7cca-4429-a0d4-cb8798fd68ee"
      STRIPE_SECRET: "sk_test_51O2alEFxYpxLheef0ZI9Vo0a4FVY1iDuTMRmooyQzS9X2h2B9GkjyRL31RRYQoOM5ItSv0cqLyrIxdlvsDd8IRM3004cnfmqXI"

    volumes:
      - ./:/main
#    ports:
#      - "10099:10099"
    network_mode: "host"
